### PR TITLE
chore: add action for running tests on pull request

### PR DESCRIPTION
**Pull request by jajugoguma**
### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

Add github action for running tests on pull request.
It shows the result of test on left side of commit id.

스크린샷 2021-07-21 오후 1 41 47

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

**Review by dongsik-yoo — APPROVED** [review]
리뷰 완료합니다. 수고하셨습니다.
젠킨스에서 지우는 거도 챙겨주세요.

**Review by lja1018 — APPROVED** [review]
리뷰완료합니다.

**Review by adhrinae — APPROVED** [review]
리뷰 완료합니다.

**Review by jwlee1108 — APPROVED** [review]
리뷰 완료합니다.

**Pull request merged**
